xlibclient.c: Fix build failure due to including server headers without first including xorg-server.h
eg:

.../include/xorg/os.h:572:1: error: expected parameter declarator [Parse Issue]
strlcpy(char *dst, const char *src, size_t siz);
^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
Found-by: Tinderbox
Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>